[package]
name = "mahjong"
version = "0.1.0"
authors = ["Maarten Bonsema <maarten.bonsema@gmail.com>"]

[dependencies]
rand = "0.3.11"
sdl2 = "0.9"

[dependencies.sdl2_image]
git = "https://github.com/xsleonard/rust-sdl2_image"
