[package]
name = "mahjong"
version = "0.1.0"
authors = ["Maarten Bonsema <maarten.bonsema@gmail.com>"]

[dependencies]
rand = "0.3"

[dependencies.sdl2]
version = "0.27"
default-features = false
features = ["image"]